### PR TITLE
Refactor isValidDomain to use regular expression

### PR DESCRIPTION
**Pull request by yassin-l**

### CODE REVIEW

**Comment by XORbit01** [comment]
test failed on domains contains numbers

**Comment by yassin-l** [comment]
I noticed a couple of issues with the new commit for the isValidDomain function. Firstly, it doesn't seem to support domains with hyphens, so any domains that include a hyphen won't count as valid domains. Additionally, it appears that the function assumes that there are only a maximum of two levels of domains, so domains like `mail.google.com` won't be considered valid domains.

**Comment by XORbit01** [comment]
multi level subdomains are considered in the regex
mail.google.com works perfectly in my last commit 
but as you said 
the hyphens are not supported 
so we need to add hyphens to the prev regex

**Comment by XORbit01** [comment]
```^([a-zA-Z0-9]+[.-])+[a-zA-Z]+$```
check this regex

**Pull request merged**
